name: Build chess project

permissions:
  contents: write

on: [push, pull_request]

env:
  UPX_VERSION: '4.1.0'
  BUILD_CONFIGURATION: Release
  SOLUTION_FILE_PATH: PdfSearch.sln
  VCPKG_PACKAGES: 'poppler:x86-windows opencv2:x86-windows'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Add MSBuild
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Setup vcpkg
      run: |
        git clone https://github.com/Microsoft/vcpkg.git
        .\vcpkg\bootstrap-vcpkg.bat
        .\vcpkg\vcpkg.exe install ${{env.VCPKG_PACKAGES}}
        .\vcpkg\vcpkg.exe integrate install

    - name: Fetch commit files
      uses: actions/checkout@v3

    - name: Restore NuGet packages
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Build
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3.1.2

      with:
        name: unpacked-build
        path: Release\

  publish-release:
    runs-on: windows-latest
    if: startsWith(github.ref, 'refs/tags/')

    needs:
      - build

    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v3

      with:
        name: release-build
        path: build-files

    - name: Release and upload artifacts
      uses: softprops/action-gh-release@v1

      with:
        files: |
          build-files/*.exe
          build-files/*.dll
